# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/baxter2/ros_ws/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/baxter2/ros_ws/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /home/baxter2/ros_ws/src && $(CMAKE_COMMAND) -E cmake_progress_start /home/baxter2/ros_ws/src/CMakeFiles /home/baxter2/ros_ws/src/vive_py/CMakeFiles/progress.marks
	cd /home/baxter2/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 vive_py/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/baxter2/ros_ws/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 vive_py/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/baxter2/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 vive_py/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 vive_py/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/baxter2/ros_ws/src && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
vive_py/CMakeFiles/vive_py_genpy.dir/rule:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 vive_py/CMakeFiles/vive_py_genpy.dir/rule
.PHONY : vive_py/CMakeFiles/vive_py_genpy.dir/rule

# Convenience name for target.
vive_py_genpy: vive_py/CMakeFiles/vive_py_genpy.dir/rule

.PHONY : vive_py_genpy

# fast build rule for target.
vive_py_genpy/fast:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f vive_py/CMakeFiles/vive_py_genpy.dir/build.make vive_py/CMakeFiles/vive_py_genpy.dir/build
.PHONY : vive_py_genpy/fast

# Convenience name for target.
vive_py/CMakeFiles/vive_py_gennodejs.dir/rule:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 vive_py/CMakeFiles/vive_py_gennodejs.dir/rule
.PHONY : vive_py/CMakeFiles/vive_py_gennodejs.dir/rule

# Convenience name for target.
vive_py_gennodejs: vive_py/CMakeFiles/vive_py_gennodejs.dir/rule

.PHONY : vive_py_gennodejs

# fast build rule for target.
vive_py_gennodejs/fast:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f vive_py/CMakeFiles/vive_py_gennodejs.dir/build.make vive_py/CMakeFiles/vive_py_gennodejs.dir/build
.PHONY : vive_py_gennodejs/fast

# Convenience name for target.
vive_py/CMakeFiles/vive_py_generate_messages_cpp.dir/rule:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 vive_py/CMakeFiles/vive_py_generate_messages_cpp.dir/rule
.PHONY : vive_py/CMakeFiles/vive_py_generate_messages_cpp.dir/rule

# Convenience name for target.
vive_py_generate_messages_cpp: vive_py/CMakeFiles/vive_py_generate_messages_cpp.dir/rule

.PHONY : vive_py_generate_messages_cpp

# fast build rule for target.
vive_py_generate_messages_cpp/fast:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f vive_py/CMakeFiles/vive_py_generate_messages_cpp.dir/build.make vive_py/CMakeFiles/vive_py_generate_messages_cpp.dir/build
.PHONY : vive_py_generate_messages_cpp/fast

# Convenience name for target.
vive_py/CMakeFiles/_vive_py_generate_messages_check_deps_AddTwoInts.dir/rule:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 vive_py/CMakeFiles/_vive_py_generate_messages_check_deps_AddTwoInts.dir/rule
.PHONY : vive_py/CMakeFiles/_vive_py_generate_messages_check_deps_AddTwoInts.dir/rule

# Convenience name for target.
_vive_py_generate_messages_check_deps_AddTwoInts: vive_py/CMakeFiles/_vive_py_generate_messages_check_deps_AddTwoInts.dir/rule

.PHONY : _vive_py_generate_messages_check_deps_AddTwoInts

# fast build rule for target.
_vive_py_generate_messages_check_deps_AddTwoInts/fast:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f vive_py/CMakeFiles/_vive_py_generate_messages_check_deps_AddTwoInts.dir/build.make vive_py/CMakeFiles/_vive_py_generate_messages_check_deps_AddTwoInts.dir/build
.PHONY : _vive_py_generate_messages_check_deps_AddTwoInts/fast

# Convenience name for target.
vive_py/CMakeFiles/_vive_py_generate_messages_check_deps_Num.dir/rule:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 vive_py/CMakeFiles/_vive_py_generate_messages_check_deps_Num.dir/rule
.PHONY : vive_py/CMakeFiles/_vive_py_generate_messages_check_deps_Num.dir/rule

# Convenience name for target.
_vive_py_generate_messages_check_deps_Num: vive_py/CMakeFiles/_vive_py_generate_messages_check_deps_Num.dir/rule

.PHONY : _vive_py_generate_messages_check_deps_Num

# fast build rule for target.
_vive_py_generate_messages_check_deps_Num/fast:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f vive_py/CMakeFiles/_vive_py_generate_messages_check_deps_Num.dir/build.make vive_py/CMakeFiles/_vive_py_generate_messages_check_deps_Num.dir/build
.PHONY : _vive_py_generate_messages_check_deps_Num/fast

# Convenience name for target.
vive_py/CMakeFiles/vive_py_generate_messages_py.dir/rule:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 vive_py/CMakeFiles/vive_py_generate_messages_py.dir/rule
.PHONY : vive_py/CMakeFiles/vive_py_generate_messages_py.dir/rule

# Convenience name for target.
vive_py_generate_messages_py: vive_py/CMakeFiles/vive_py_generate_messages_py.dir/rule

.PHONY : vive_py_generate_messages_py

# fast build rule for target.
vive_py_generate_messages_py/fast:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f vive_py/CMakeFiles/vive_py_generate_messages_py.dir/build.make vive_py/CMakeFiles/vive_py_generate_messages_py.dir/build
.PHONY : vive_py_generate_messages_py/fast

# Convenience name for target.
vive_py/CMakeFiles/vive_py_generate_messages.dir/rule:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 vive_py/CMakeFiles/vive_py_generate_messages.dir/rule
.PHONY : vive_py/CMakeFiles/vive_py_generate_messages.dir/rule

# Convenience name for target.
vive_py_generate_messages: vive_py/CMakeFiles/vive_py_generate_messages.dir/rule

.PHONY : vive_py_generate_messages

# fast build rule for target.
vive_py_generate_messages/fast:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f vive_py/CMakeFiles/vive_py_generate_messages.dir/build.make vive_py/CMakeFiles/vive_py_generate_messages.dir/build
.PHONY : vive_py_generate_messages/fast

# Convenience name for target.
vive_py/CMakeFiles/vive_py_gencpp.dir/rule:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 vive_py/CMakeFiles/vive_py_gencpp.dir/rule
.PHONY : vive_py/CMakeFiles/vive_py_gencpp.dir/rule

# Convenience name for target.
vive_py_gencpp: vive_py/CMakeFiles/vive_py_gencpp.dir/rule

.PHONY : vive_py_gencpp

# fast build rule for target.
vive_py_gencpp/fast:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f vive_py/CMakeFiles/vive_py_gencpp.dir/build.make vive_py/CMakeFiles/vive_py_gencpp.dir/build
.PHONY : vive_py_gencpp/fast

# Convenience name for target.
vive_py/CMakeFiles/vive_py_generate_messages_nodejs.dir/rule:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 vive_py/CMakeFiles/vive_py_generate_messages_nodejs.dir/rule
.PHONY : vive_py/CMakeFiles/vive_py_generate_messages_nodejs.dir/rule

# Convenience name for target.
vive_py_generate_messages_nodejs: vive_py/CMakeFiles/vive_py_generate_messages_nodejs.dir/rule

.PHONY : vive_py_generate_messages_nodejs

# fast build rule for target.
vive_py_generate_messages_nodejs/fast:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f vive_py/CMakeFiles/vive_py_generate_messages_nodejs.dir/build.make vive_py/CMakeFiles/vive_py_generate_messages_nodejs.dir/build
.PHONY : vive_py_generate_messages_nodejs/fast

# Convenience name for target.
vive_py/CMakeFiles/vive_py_generate_messages_eus.dir/rule:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 vive_py/CMakeFiles/vive_py_generate_messages_eus.dir/rule
.PHONY : vive_py/CMakeFiles/vive_py_generate_messages_eus.dir/rule

# Convenience name for target.
vive_py_generate_messages_eus: vive_py/CMakeFiles/vive_py_generate_messages_eus.dir/rule

.PHONY : vive_py_generate_messages_eus

# fast build rule for target.
vive_py_generate_messages_eus/fast:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f vive_py/CMakeFiles/vive_py_generate_messages_eus.dir/build.make vive_py/CMakeFiles/vive_py_generate_messages_eus.dir/build
.PHONY : vive_py_generate_messages_eus/fast

# Convenience name for target.
vive_py/CMakeFiles/vive_py_geneus.dir/rule:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 vive_py/CMakeFiles/vive_py_geneus.dir/rule
.PHONY : vive_py/CMakeFiles/vive_py_geneus.dir/rule

# Convenience name for target.
vive_py_geneus: vive_py/CMakeFiles/vive_py_geneus.dir/rule

.PHONY : vive_py_geneus

# fast build rule for target.
vive_py_geneus/fast:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f vive_py/CMakeFiles/vive_py_geneus.dir/build.make vive_py/CMakeFiles/vive_py_geneus.dir/build
.PHONY : vive_py_geneus/fast

# Convenience name for target.
vive_py/CMakeFiles/vive_py_generate_messages_lisp.dir/rule:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 vive_py/CMakeFiles/vive_py_generate_messages_lisp.dir/rule
.PHONY : vive_py/CMakeFiles/vive_py_generate_messages_lisp.dir/rule

# Convenience name for target.
vive_py_generate_messages_lisp: vive_py/CMakeFiles/vive_py_generate_messages_lisp.dir/rule

.PHONY : vive_py_generate_messages_lisp

# fast build rule for target.
vive_py_generate_messages_lisp/fast:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f vive_py/CMakeFiles/vive_py_generate_messages_lisp.dir/build.make vive_py/CMakeFiles/vive_py_generate_messages_lisp.dir/build
.PHONY : vive_py_generate_messages_lisp/fast

# Convenience name for target.
vive_py/CMakeFiles/vive_py_genlisp.dir/rule:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 vive_py/CMakeFiles/vive_py_genlisp.dir/rule
.PHONY : vive_py/CMakeFiles/vive_py_genlisp.dir/rule

# Convenience name for target.
vive_py_genlisp: vive_py/CMakeFiles/vive_py_genlisp.dir/rule

.PHONY : vive_py_genlisp

# fast build rule for target.
vive_py_genlisp/fast:
	cd /home/baxter2/ros_ws/src && $(MAKE) -f vive_py/CMakeFiles/vive_py_genlisp.dir/build.make vive_py/CMakeFiles/vive_py_genlisp.dir/build
.PHONY : vive_py_genlisp/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... install/local"
	@echo "... vive_py_genpy"
	@echo "... vive_py_gennodejs"
	@echo "... vive_py_generate_messages_cpp"
	@echo "... _vive_py_generate_messages_check_deps_AddTwoInts"
	@echo "... edit_cache"
	@echo "... _vive_py_generate_messages_check_deps_Num"
	@echo "... test"
	@echo "... vive_py_generate_messages_py"
	@echo "... vive_py_generate_messages"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... vive_py_gencpp"
	@echo "... vive_py_generate_messages_nodejs"
	@echo "... vive_py_generate_messages_eus"
	@echo "... vive_py_geneus"
	@echo "... vive_py_generate_messages_lisp"
	@echo "... vive_py_genlisp"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/baxter2/ros_ws/src && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

