set(_CATKIN_CURRENT_PACKAGE "vive_py")
set(vive_py_VERSION "0.0.0")
set(vive_py_MAINTAINER "baxter2 <baxter2@todo.todo>")
set(vive_py_PACKAGE_FORMAT "1")
set(vive_py_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(vive_py_BUILD_EXPORT_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(vive_py_BUILDTOOL_DEPENDS "catkin")
set(vive_py_BUILDTOOL_EXPORT_DEPENDS )
set(vive_py_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(vive_py_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(vive_py_TEST_DEPENDS )
set(vive_py_DOC_DEPENDS )
set(vive_py_URL_WEBSITE "")
set(vive_py_URL_BUGTRACKER "")
set(vive_py_URL_REPOSITORY "")
set(vive_py_DEPRECATED "")